name: Terraform Dev

permissions:
      checks: write
      contents: read
      statuses: write
      id-token: write # Require write permission to Fetch an OIDC token.
      pull-requests: write # Required to create a pull request check run.

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
    paths:
      - 'rg-ncu-terraform/**'
      - '.github/workflows/tf_deploy.yml'
      - '.github/workflows/tf_dev.yml'
  # Trigger on push to dev branch
  push:
    branches:
      - dev
    paths:
      - 'rg-ncu-terraform/**'
      - '.github/workflows/tf_deploy.yml'
      - '.github/workflows/tf_dev.yml'

jobs:
  call-deploy:
    uses: ./.github/workflows/tf_deploy.yml
    with:
      environment: AzureDev
      backend_config: backend-dev.tfbackend
      varfile_config: dev.tfvars
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}